# Data Visualization and Data Preparation

## 1 Visualization and Analysis of Traffic Data

In [3]:
import numpy as np

# 读取文件
adj = np.load("./dataset/PEMS08/adj.npy")
flow = np.load("./dataset/PEMS08/flow.npy")

# 打印结构信息
print("✅ adj.npy 信息:")
print(f"  类型: {type(adj)}")
print(f"  形状: {adj.shape}")
print(f"  数据类型: {adj.dtype}")
print("  内容预览(前5x5子矩阵):")
print(adj[:5, :5])

print("\n✅ flow.npy 信息:")
print(f"  类型: {type(flow)}")
print(f"  形状: {flow.shape}")
print(f"  数据类型: {flow.dtype}")
print("  内容预览(前1个样本):")
print(flow[0])

✅ adj.npy 信息:
  类型: <class 'numpy.ndarray'>
  形状: (170, 170)
  数据类型: float32
  内容预览(前5x5子矩阵):
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

✅ flow.npy 信息:
  类型: <class 'numpy.ndarray'>
  形状: (17856, 170, 3)
  数据类型: float64
  内容预览(前1个样本):
[[1.330e+02 6.030e-02 6.580e+01]
 [2.100e+02 5.890e-02 6.960e+01]
 [1.240e+02 3.580e-02 6.580e+01]
 [1.450e+02 4.160e-02 6.960e+01]
 [2.060e+02 4.930e-02 6.940e+01]
 [5.800e+01 1.470e-02 7.080e+01]
 [2.480e+02 7.320e-02 6.890e+01]
 [1.170e+02 6.780e-02 6.490e+01]
 [4.400e+01 2.950e-02 6.840e+01]
 [2.560e+02 3.850e-02 6.890e+01]
 [2.510e+02 4.620e-02 6.550e+01]
 [1.430e+02 5.310e-02 6.670e+01]
 [8.600e+01 2.290e-02 6.850e+01]
 [1.550e+02 6.280e-02 6.860e+01]
 [1.480e+02 3.410e-02 6.840e+01]
 [1.040e+02 2.610e-02 7.040e+01]
 [2.900e+01 2.010e-02 6.500e+01]
 [8.600e+01 2.290e-02 6.840e+01]
 [1.410e+02 3.470e-02 6.850e+01]
 [9.400e+01 2.570e-02 6.980e+01]
 [9.900e+01 2.250e-02 6.880e+01]
 [8.900e+01 3.940e-01 7

## 2 Data Prepocess for Covid Data (US States)

需要输入的特征包括 #confirmed, #deaths, (#Recovered, #Motality-Rate, #Testing-Rate,) #Population

数据来源可以是JHU数据（不够全）还有NYTimes

### Adj

In [3]:
import numpy as np

# 读取文件
adj = np.load("./dataset/COVID/dynamic_adj.npy")
flow = np.load("./dataset/PEMS08/flow.npy")

# 打印结构信息
print("✅ adj.npy 信息:")
print(f"  类型: {type(adj)}")
print(f"  形状: {adj.shape}")
print(f"  数据类型: {adj.dtype}")
print("  内容预览(前5x5子矩阵):")

✅ adj.npy 信息:
  类型: <class 'numpy.ndarray'>
  形状: (366, 52, 52)
  数据类型: float32
  内容预览(前5x5子矩阵):


In [4]:
np.sum(adj[0, :, :])

29.667946

In [6]:
flow.shape

(17856, 170, 3)

In [16]:
17856/366

48.78688524590164